# Generated by Django 3.2.8 on 2022-04-04 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Warhouse', models.CharField(max_length=30)),
                ('Qty', models.IntegerField()),
                ('serial_num', models.IntegerField()),
                ('color', models.CharField(blank=True, max_length=30, null=True)),
                ('model_type', models.CharField(max_length=30)),
                ('capisty', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
    ]
